service: bluesky-feeds

provider:
  name: aws
  region: us-west-2
  runtime: nodejs18.x
  stage: ${opt:stage, 'development'}
  timeout: 28
  memorySize: 1024
  deploymentBucket:
    name: ${ssm:deployment-artifacts-bucket}
  environment:
    PUBLIC_HOSTNAME: ${self:custom.customDomain.domainName}
    SYNC_SUBSCRIBER_QUEUE_TABLE: ${self:custom.syncSubscriberQueueTable}
    SUBSCRIBER_FOLLOWING_TABLE: ${self:custom.subscriberFollowingTable}
    MUTE_WORDS_TABLE: ${self:custom.muteWordsTable}
    APP_STATUS_TABLE: ${self:custom.appStatusTable}
    BLUESKY_SERVICE_USER_DID: ${ssm:/bluesky-feeds/${self:provider.stage}/service/user-did}


custom:
  prune:
    automatic: true
    number: 3
  serverless-iam-roles-per-function:
    defaultInherit: true
  customDomain:
    domainName: ${ssm:/bluesky-feeds/${self:provider.stage}/domain-name}
    certificateArn: ${ssm:/bluesky-feeds/${self:provider.stage}/certificate-arn}
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
  syncSubscriberQueueTable: ${self:service}-${self:provider.stage}-sync-subscriber-queue
  subscriberFollowingTable: ${self:service}-${self:provider.stage}-subscriber-following
  muteWordsTable: ${self:service}-${self:provider.stage}-mute-words
  appStatusTable: ${self:service}-${self:provider.stage}-app-status
  blueskyAuth:
    identifier: ${ssm:/bluesky-feeds/${self:provider.stage}/service/identifier}
    password: ${ssm:/bluesky-feeds/${self:provider.stage}/service/password}
  enablePolling:
    development: false
    production: true

	
plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

functions:
  did:
    handler: ./src/endpoints/did/index.handler
    events:
     - httpApi: GET /.well-known/did.json

  getFeedSkeleton:
    handler: ./src/endpoints/getFeedSkeleton/index.handler
    events:
     - httpApi: GET /xrpc/app.bsky.feed.getFeedSkeleton
    environment:
      BLUESKY_SERVICE_IDENTIFIER: ${self:custom.blueskyAuth.identifier}
      BLUESKY_SERVICE_PASSWORD: ${self:custom.blueskyAuth.password}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
        Resource:
          - !GetAtt SubscriberFollowingTable.Arn
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource:
          - !GetAtt MuteWordsTable.Arn
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - !GetAtt SyncSubscriberQueueTable.Arn

  notificationListener:
    handler: ./src/endpoints/notificationListener/index.handler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: ${self:custom.enablePolling.${self:provider.stage}}
    environment:
      BLUESKY_SERVICE_IDENTIFIER: ${self:custom.blueskyAuth.identifier}
      BLUESKY_SERVICE_PASSWORD: ${self:custom.blueskyAuth.password}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:DeleteItem
        Resource:
          - !GetAtt MuteWordsTable.Arn
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource:
          - !GetAtt SyncSubscriberQueueTable.Arn

  syncSubscriberFollowing:
    handler: ./src/endpoints/syncSubscriberFollowing/index.handler
    events:	
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [SyncSubscriberQueueTable, StreamArn]
          startingPosition: LATEST
          batchSize: 1
          maximumRetryAttempts: 5
          filterPatterns:
            - eventName: [INSERT, MODIFY]
    environment:
      BLUESKY_SERVICE_IDENTIFIER: ${self:custom.blueskyAuth.identifier}
      BLUESKY_SERVICE_PASSWORD: ${self:custom.blueskyAuth.password}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - !GetAtt SyncSubscriberQueueTable.Arn
          - !GetAtt SubscriberFollowingTable.Arn

resources:
  Resources:
    SyncSubscriberQueueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.syncSubscriberQueueTable}
        AttributeDefinitions:
          - AttributeName: subscriberDid
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: subscriberDid
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    SubscriberFollowingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.subscriberFollowingTable}
        AttributeDefinitions:
          - AttributeName: subscriberDid
            AttributeType: S
          - AttributeName: qualifier
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: subscriberDid
            KeyType: HASH
          - AttributeName: qualifier
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    MuteWordsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.muteWordsTable}
        AttributeDefinitions:
          - AttributeName: subscriberDid
            AttributeType: S
          - AttributeName: muteWord
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: subscriberDid
            KeyType: HASH
          - AttributeName: muteWord
            KeyType: RANGE

    AppStatusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.appStatusTable}
        AttributeDefinitions:
          - AttributeName: setting
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: setting
            KeyType: HASH